#!/bin/bash
# build_kindle.sh
# Automates the configuration, patching, and compilation of the Kindle PW3 port.

set -e

echo "=> Compiling Mini vMac setup tool..."
gcc setup/tool.c -o setup_t

echo "=> Generating configuration for Linux ARM..."
./setup_t -t larm -hres 1440 -vres 1056 > setup.sh
chmod +x setup.sh
./setup.sh

echo "=> Patching the generated Makefile..."
# 1. Swap OSGLUXWN for OSGLUKND everywhere
sed -i 's/OSGLUXWN/OSGLUKND/g' Makefile

# 2. Force the cross-compiler
sed -i 's/gcc /arm-linux-gnueabihf-gcc /g' Makefile

# 3. Inject the ARM sysroot include directory
sed -i 's|-Isrc/|-Isrc/ -I/usr/arm-linux-gnueabihf/include|g' Makefile

# 4. Strip X11 includes
sed -i 's|-I/usr/X11R6/include||g' Makefile

# 5. OBLITERATE X11 and inject FBInk + standard math library (-lm)
# We target the literal strings generated by setup_t
sed -i 's|-L/usr/X11R6/lib -lX11|-L/usr/arm-linux-gnueabihf/lib -lfbink -lm|g' Makefile
sed -i 's|-lX11|-L/usr/arm-linux-gnueabihf/lib -lfbink -lm|g' Makefile

echo "=> Cross-compiling the emulator..."
make

echo "=> Build successful! Binary is ready for deployment."
