/*
 * kindle/MYOSGLUE.c  —  Mini vMac OS Glue for Kindle Paperwhite 3
 *
 * This file is dropped in place of the SDL2 MYOSGLUE.c that setup_t
 * symlinks into the build directory.  It is compiled as part of the
 * normal Mini vMac build; CNFGRAPI.h (generated by setup.sh) must be
 * present alongside it so the Mini vMac type macros resolve correctly.
 *
 * Generated with:
 *   ./setup_t -t larm -m Plus -api sd2 \
 *             -emm 0 -fullscreen 1 -var-fullscreen 0 -sound 0 -iid 1
 *
 * ── Display ────────────────────────────────────────────────────────────
 *  Mac 1bpp 512×342  →  unpack  →  2× scale  →  90° CCW rotate
 *  →  write /dev/fb0  (758×1024 @ Y8 grayscale)
 *  →  ioctl MXCFB_SEND_UPDATE  (A2 every frame, GC16 every ~5 s)
 *
 * ── Touch ──────────────────────────────────────────────────────────────
 *  evdev Type-B MT  →  normalise  →  rotate to landscape logical space
 *  →  (x/2, (y-37)/2)  →  CurMouseH / CurMouseV   (absolute, direct)
 *
 * ── On-screen keyboard ─────────────────────────────────────────────────
 *  Tap top-right corner (lx ≥ 950, ly ≤ 50) to toggle.
 *  Hardware page-turn buttons → Space / Delete.
 */

/* ── Mini vMac generated header ─────────────────────────────────────── *
 * CNFGRAPI.h is written by setup.sh into the build directory.          *
 * It defines ui3r/ui4r/blnr/trueblnr/falseblnr/LOCALPROC/GLOBALPROC.  */
#include "CNFGRAPI.h"

/* ── Linux / POSIX ───────────────────────────────────────────────────── */
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <linux/fb.h>
#include <linux/input.h>
#include <sys/ioctl.h>
#include <sys/mman.h>

/* ── Mini vMac core symbols (from GLOBGLUE.c / COMOSGLU.c) ──────────── *
 * Forward declarations only — the linker resolves these from the other  *
 * compiled translation units.                                           */

/* 1-bpp Mac screen buffer: 64 bytes/row, MSB first, 0=white 1=black.   */
extern ui3r *screencurrentbuff;

/* vMacScreenWidth = 512, vMacScreenHeight = 342 (set by generated cfg) */
extern uint16_t vMacScreenWidth;
extern uint16_t vMacScreenHeight;

/* Mouse state — we write these; the core reads them every tick.        */
extern uint16_t CurMouseH;
extern uint16_t CurMouseV;
extern blnr     CurMouseButton;

/* Keyboard: ADB keycode + down/up.                                     */
extern void Keyboard_UpdateKeyMap2(int key, blnr isdown);

/* Run one emulated 60 Hz tick.                                         */
extern void DoEmulateOneTick(void);

/* Platform state init (zeros our vars in COMOSGLU).                    */
extern void ZapOSGLUVars(void);

/* Memory allocation for the emulator core.  Returns trueblnr on ok.   */
extern blnr ReserveAllocAll(void);
extern void UnReserveAlloc(void);

/* ── MXCFB eink driver  (Kindle 5.x, Freescale i.MX6 EPDC) ─────────── */
#define MXCFB_SEND_UPDATE _IOW('F', 0x2E, struct mxcfb_update_data)

struct mxcfb_rect { uint32_t top, left, width, height; };

struct mxcfb_alt_buffer_data {
    uint32_t phys_addr, width, height;
    struct mxcfb_rect alt_update_region;
};

struct mxcfb_update_data {
    struct mxcfb_rect        update_region;
    uint32_t                 waveform_mode;
    uint32_t                 update_mode;
    uint32_t                 update_marker;
    int32_t                  temp;
    uint32_t                 flags;
    int32_t                  dither_mode;
    int32_t                  quant_bit;
    struct mxcfb_alt_buffer_data alt_buffer_data;
};

#define WAVEFORM_MODE_DU    0x01   /* fast 2-level, mild ghost       */
#define WAVEFORM_MODE_GC16  0x02   /* full 16-level grayscale, slow  */
#define WAVEFORM_MODE_A2    0x06   /* very fast 2-level (animation)  */
#define UPDATE_MODE_PARTIAL 0x00
#define UPDATE_MODE_FULL    0x01
#define TEMP_USE_AMBIENT    0x1000

/* ── Display geometry ────────────────────────────────────────────────── */
#define MAC_W     512
#define MAC_H     342
#define SCALE     2

/* Landscape logical space:  1024 × 758                                 */
#define LOG_W     (MAC_W * SCALE)           /* 1024                     */
#define LOG_H_MAC (MAC_H * SCALE)           /* 684 — Mac content height */

/* Physical portrait framebuffer                                         */
#define FB_W      758
#define FB_H      1024

/* Top/bottom margin to centre Mac content in landscape height:
 *   (758 - 684) / 2 = 37 px                                           */
#define MAC_OFF_Y ((FB_W - LOG_H_MAC) / 2)  /* 37                      */

/*
 * Landscape → portrait (90° CCW rotation):
 *   portrait_col = FB_W − 1 − landscape_y
 *   portrait_row = landscape_x
 *
 * Inverse (touch → landscape):
 *   landscape_x  = portrait_row
 *   landscape_y  = FB_W − 1 − portrait_col
 */
#define L2P_COL(ly) (FB_W - 1 - (ly))
#define L2P_ROW(lx) (lx)

/* ── ADB keycodes ────────────────────────────────────────────────────── */
#define ADB_A 0  #define ADB_S 1  #define ADB_D 2  #define ADB_F 3
#define ADB_H 4  #define ADB_G 5  #define ADB_Z 6  #define ADB_X 7
#define ADB_C 8  #define ADB_V 9  #define ADB_B 11 #define ADB_Q 12
#define ADB_W 13 #define ADB_E 14 #define ADB_R 15 #define ADB_Y 16
#define ADB_T 17 #define ADB_1 18 #define ADB_2 19 #define ADB_3 20
#define ADB_4 21 #define ADB_6 22 #define ADB_5 23 #define ADB_0 29
#define ADB_9 25 #define ADB_7 26 #define ADB_8 28 #define ADB_O 31
#define ADB_U 32 #define ADB_I 34 #define ADB_P 35 #define ADB_RET 36
#define ADB_L 37 #define ADB_J 38 #define ADB_K 40 #define ADB_SC 41
#define ADB_N 45 #define ADB_M 46 #define ADB_CO 43 #define ADB_DO 47
#define ADB_SL 44 #define ADB_TAB 48 #define ADB_SPC 49
#define ADB_DEL 51 #define ADB_ESC 53 #define ADB_CMD 55
#define ADB_SHF 56 #define ADB_OPT 58 #define ADB_CTL 59
#define ADB_LT 123 #define ADB_RT 124 #define ADB_DN 125 #define ADB_UP 126

/* ── On-screen keyboard layout ──────────────────────────────────────── */
typedef struct { const char *label; int adb; int w; } Key;

static const Key ROW0[] = {
    {"ESC",ADB_ESC,70},  {"1",ADB_1,62},  {"2",ADB_2,62},  {"3",ADB_3,62},
    {"4",ADB_4,62},      {"5",ADB_5,62},  {"6",ADB_6,62},  {"7",ADB_7,62},
    {"8",ADB_8,62},      {"9",ADB_9,62},  {"0",ADB_0,62},  {"DEL",ADB_DEL,82},
    {NULL,0,0}};
static const Key ROW1[] = {
    {"TAB",ADB_TAB,82},  {"Q",ADB_Q,62},  {"W",ADB_W,62},  {"E",ADB_E,62},
    {"R",ADB_R,62},      {"T",ADB_T,62},  {"Y",ADB_Y,62},  {"U",ADB_U,62},
    {"I",ADB_I,62},      {"O",ADB_O,62},  {"P",ADB_P,62},  {"RET",ADB_RET,82},
    {NULL,0,0}};
static const Key ROW2[] = {
    {"CTL",ADB_CTL,82},  {"A",ADB_A,62},  {"S",ADB_S,62},  {"D",ADB_D,62},
    {"F",ADB_F,62},      {"G",ADB_G,62},  {"H",ADB_H,62},  {"J",ADB_J,62},
    {"K",ADB_K,62},      {"L",ADB_L,62},  {";",ADB_SC,62}, {"'",38,124},
    {NULL,0,0}};
static const Key ROW3[] = {
    {"SHF",ADB_SHF,106},{"Z",ADB_Z,62},  {"X",ADB_X,62},  {"C",ADB_C,62},
    {"V",ADB_V,62},      {"B",ADB_B,62},  {"N",ADB_N,62},  {"M",ADB_M,62},
    {",",ADB_CO,62},     {".",ADB_DO,62}, {"/",ADB_SL,62}, {"SHF",ADB_SHF,106},
    {NULL,0,0}};
static const Key ROW4[] = {
    {"CMD",ADB_CMD,106}, {"OPT",ADB_OPT,82},
    {"       SPACE       ",ADB_SPC,400},
    {"OPT",ADB_OPT,82},
    {"<",ADB_LT,64},{"/\\",ADB_UP,64},{"V",ADB_DN,64},{">",ADB_RT,64},
    {NULL,0,0}};

static const Key *ROWS[] = {ROW0, ROW1, ROW2, ROW3, ROW4};
#define KBD_NROWS    5
#define KBD_KEY_H    50
#define KBD_START_LY (FB_W - KBD_NROWS * KBD_KEY_H)   /* 508 */

/* ── Global state ────────────────────────────────────────────────────── */
static int      fb_fd     = -1;
static uint8_t *fb_mem    = NULL;
static size_t   fb_size;
static uint32_t fb_stride;        /* real bytes/row from fscreeninfo    */

static int  touch_fd  = -1;
static int  tx_min = 0, tx_max = 4095;
static int  ty_min = 0, ty_max = 4095;

#define MAX_SLOTS 5
static int cur_slot  = 0;
static int slot_id[MAX_SLOTS];
static int slot_x [MAX_SLOTS];
static int slot_y [MAX_SLOTS];
static int active_slot  = -1;
static int touch_active = 0;

static int kbd_visible = 0;
static int shift_down  = 0;

static volatile int g_quit  = 0;
static uint32_t     upd_seq = 1;

/* ── Timing ──────────────────────────────────────────────────────────── */
LOCALFUNC int64_t time_us(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (int64_t)ts.tv_sec * 1000000LL + ts.tv_nsec / 1000;
}
LOCALPROC sleep_us(int64_t us) {
    if (us <= 0) return;
    struct timespec ts = { us / 1000000, (us % 1000000) * 1000 };
    nanosleep(&ts, NULL);
}

/* ── Signal ──────────────────────────────────────────────────────────── */
static void on_signal(int s) { (void)s; g_quit = 1; }

/* ── eink update ─────────────────────────────────────────────────────── *
 * Mac content in portrait coords:                                        *
 *   cols [MAC_OFF_Y … MAC_OFF_Y+LOG_H_MAC-1]  =  [37 … 720]            *
 *   rows [0 … LOG_W-1]                         =  [0 … 1023]           */
LOCALPROC eink_send(uint32_t waveform, uint32_t mode,
                    uint32_t top, uint32_t left,
                    uint32_t height, uint32_t width) {
    struct mxcfb_update_data u;
    memset(&u, 0, sizeof(u));
    u.update_region.top    = top;
    u.update_region.left   = left;
    u.update_region.height = height;
    u.update_region.width  = width;
    u.waveform_mode         = waveform;
    u.update_mode           = mode;
    u.update_marker         = upd_seq++;
    u.temp                  = TEMP_USE_AMBIENT;
    ioctl(fb_fd, MXCFB_SEND_UPDATE, &u);
}

LOCALPROC eink_update_mac(uint32_t waveform) {
    eink_send(waveform, UPDATE_MODE_PARTIAL,
              0, MAC_OFF_Y, LOG_W, LOG_H_MAC);
}
LOCALPROC eink_full_gc16(void) {
    eink_send(WAVEFORM_MODE_GC16, UPDATE_MODE_FULL, 0, 0, FB_H, FB_W);
}

/* ── Pixel helpers ───────────────────────────────────────────────────── */
static inline void set_px(int lx, int ly, uint8_t g) {
    int pcol = L2P_COL(ly);
    int prow = L2P_ROW(lx);
    if ((unsigned)pcol < FB_W && (unsigned)prow < FB_H)
        fb_mem[prow * fb_stride + pcol] = g;
}
LOCALPROC fill_rect(int lx, int ly, int lw, int lh, uint8_t g) {
    for (int dy = 0; dy < lh; dy++)
        for (int dx = 0; dx < lw; dx++)
            set_px(lx+dx, ly+dy, g);
}

/* ── Mac screen → framebuffer ────────────────────────────────────────── *
 * Called by Mini vMac core whenever the Mac screen changes.             */
GLOBALPROC HaveChangedScreenBuff(ui4r top, ui4r left,
                                  ui4r bottom, ui4r right) {
    if (!fb_mem || !screencurrentbuff) return;
    if (top    > MAC_H) top    = MAC_H;
    if (bottom > MAC_H) bottom = MAC_H;
    if (left   > MAC_W) left   = MAC_W;
    if (right  > MAC_W) right  = MAC_W;

    for (int my = (int)top; my < (int)bottom; my++) {
        const ui3r *row = screencurrentbuff + my * (MAC_W / 8);
        for (int mx = (int)left; mx < (int)right; mx++) {
            int bit   = (row[mx >> 3] >> (7 - (mx & 7))) & 1;
            uint8_t g = bit ? 0x00 : 0xFF;   /* 1=black, 0=white */
            int lx = mx * SCALE;
            int ly = MAC_OFF_Y + my * SCALE;
            set_px(lx,   ly,   g);
            set_px(lx+1, ly,   g);
            set_px(lx,   ly+1, g);
            set_px(lx+1, ly+1, g);
        }
    }
    eink_update_mac(WAVEFORM_MODE_A2);
}

/* ── On-screen keyboard ──────────────────────────────────────────────── */
LOCALPROC draw_key(int lx, int ly, int lw, int lh, int pressed) {
    fill_rect(lx,   ly,   lw,   lh,   0x00);          /* border  */
    fill_rect(lx+1, ly+1, lw-2, lh-2, pressed ? 0x20 : 0xCC);
}
LOCALPROC render_keyboard(void) {
    for (int r = 0; r < KBD_NROWS; r++) {
        int lx = 0, ly = KBD_START_LY + r * KBD_KEY_H;
        for (const Key *k = ROWS[r]; k->label; k++) {
            int pressed = (k->adb == ADB_SHF && shift_down);
            draw_key(lx, ly, k->w, KBD_KEY_H, pressed);
            lx += k->w;
        }
        if (lx < LOG_W) fill_rect(lx, ly, LOG_W-lx, KBD_KEY_H, 0x88);
    }
}
LOCALPROC draw_kbd_indicator(void) {
    fill_rect(960, 2, 62, 36, 0x00);
    fill_rect(961, 3, 60, 34, kbd_visible ? 0x20 : 0x99);
}

/* ── Touch coordinate transforms ─────────────────────────────────────── */
LOCALPROC raw_to_landscape(int rx, int ry, int *lx, int *ly) {
    int xr = tx_max - tx_min; if (xr <= 0) xr = 1;
    int yr = ty_max - ty_min; if (yr <= 0) yr = 1;
    int pc = (rx - tx_min) * (FB_W - 1) / xr;
    int pr = (ry - ty_min) * (FB_H - 1) / yr;
    pc = pc < 0 ? 0 : pc > FB_W-1 ? FB_W-1 : pc;
    pr = pr < 0 ? 0 : pr > FB_H-1 ? FB_H-1 : pr;
    *lx = pr;
    *ly = FB_W - 1 - pc;
}
LOCALPROC landscape_to_mac(int lx, int ly, int *mx, int *my) {
    *mx = lx / SCALE;
    *my = (ly - MAC_OFF_Y) / SCALE;
    if (*mx < 0)      *mx = 0;
    if (*mx >= MAC_W) *mx = MAC_W - 1;
    if (*my < 0)      *my = 0;
    if (*my >= MAC_H) *my = MAC_H - 1;
}

/* ── Keyboard hit-test ───────────────────────────────────────────────── */
LOCALFUNC int find_key(int lx, int ly) {
    if (ly < KBD_START_LY) return -1;
    int row = (ly - KBD_START_LY) / KBD_KEY_H;
    if (row < 0 || row >= KBD_NROWS) return -1;
    int x = 0;
    for (const Key *k = ROWS[row]; k->label; k++) {
        if (lx >= x && lx < x + k->w) return k->adb;
        x += k->w;
    }
    return -1;
}

/* ── Touch event dispatch ────────────────────────────────────────────── */
LOCALPROC on_touch_down(int lx, int ly) {
    /* Top-right corner: toggle keyboard */
    if (lx >= 950 && ly <= 50) {
        kbd_visible = !kbd_visible;
        if (kbd_visible) {
            render_keyboard();
        } else {
            /* Re-blit Mac content over keyboard area */
            HaveChangedScreenBuff(
                (KBD_START_LY - MAC_OFF_Y) / SCALE, 0, MAC_H, MAC_W);
        }
        draw_kbd_indicator();
        eink_full_gc16();
        return;
    }
    if (kbd_visible && ly >= KBD_START_LY) {
        int adb = find_key(lx, ly);
        if (adb < 0) return;
        if (adb == ADB_SHF) {
            shift_down = !shift_down;
            Keyboard_UpdateKeyMap2(ADB_SHF, shift_down);
            render_keyboard();
            eink_update_mac(WAVEFORM_MODE_DU);
        } else {
            if (shift_down) Keyboard_UpdateKeyMap2(ADB_SHF, trueblnr);
            Keyboard_UpdateKeyMap2(adb, trueblnr);
        }
        return;
    }
    int mx, my;
    landscape_to_mac(lx, ly, &mx, &my);
    CurMouseH      = (uint16_t)mx;
    CurMouseV      = (uint16_t)my;
    CurMouseButton = trueblnr;
}
LOCALPROC on_touch_move(int lx, int ly) {
    if (kbd_visible && ly >= KBD_START_LY) return;
    int mx, my;
    landscape_to_mac(lx, ly, &mx, &my);
    CurMouseH = (uint16_t)mx;
    CurMouseV = (uint16_t)my;
}
LOCALPROC on_touch_up(int lx, int ly) {
    if (kbd_visible && ly >= KBD_START_LY) {
        int adb = find_key(lx, ly);
        if (adb >= 0 && adb != ADB_SHF) {
            Keyboard_UpdateKeyMap2(adb, falseblnr);
            if (shift_down) {
                Keyboard_UpdateKeyMap2(ADB_SHF, falseblnr);
                shift_down = 0;
                render_keyboard();
                eink_update_mac(WAVEFORM_MODE_DU);
            }
        }
        return;
    }
    CurMouseButton = falseblnr;
}

/* ── evdev poll (non-blocking) ───────────────────────────────────────── */
LOCALPROC poll_touch(void) {
    struct input_event ev;
    for (;;) {
        ssize_t n = read(touch_fd, &ev, sizeof(ev));
        if (n < 0) { if (errno == EAGAIN || errno == EWOULDBLOCK) break; continue; }
        if (n != (ssize_t)sizeof(ev)) break;

        if (ev.type == EV_ABS) {
            switch (ev.code) {
            case ABS_MT_SLOT:
                cur_slot = ev.value;
                if (cur_slot >= MAX_SLOTS) cur_slot = MAX_SLOTS-1;
                break;
            case ABS_MT_TRACKING_ID:
                slot_id[cur_slot] = ev.value;
                if (ev.value == -1 && cur_slot == active_slot) {
                    int lx, ly;
                    raw_to_landscape(slot_x[cur_slot], slot_y[cur_slot], &lx, &ly);
                    on_touch_up(lx, ly);
                    active_slot = -1; touch_active = 0;
                }
                break;
            case ABS_MT_POSITION_X: slot_x[cur_slot] = ev.value; break;
            case ABS_MT_POSITION_Y: slot_y[cur_slot] = ev.value; break;
            case ABS_X: slot_x[0] = ev.value; break;
            case ABS_Y: slot_y[0] = ev.value; break;
            }
        } else if (ev.type == EV_SYN && ev.code == SYN_REPORT) {
            if (active_slot < 0 && slot_id[cur_slot] != -1)
                active_slot = cur_slot;
            if (active_slot >= 0 && slot_id[active_slot] != -1) {
                int lx, ly;
                raw_to_landscape(slot_x[active_slot], slot_y[active_slot], &lx, &ly);
                if (!touch_active) { touch_active = 1; on_touch_down(lx, ly); }
                else                                    on_touch_move(lx, ly);
            }
        } else if (ev.type == EV_KEY) {
            switch (ev.code) {
            case KEY_PAGEDOWN: case KEY_NEXTSONG:
                Keyboard_UpdateKeyMap2(ADB_SPC, ev.value ? trueblnr : falseblnr);
                break;
            case KEY_PAGEUP: case KEY_PREVIOUSSONG:
                Keyboard_UpdateKeyMap2(ADB_DEL, ev.value ? trueblnr : falseblnr);
                break;
            }
        }
    }
}

/* ── Platform init / teardown ────────────────────────────────────────── */
LOCALFUNC blnr fb_open(void) {
    const char *dev = getenv("MINIVMAC_FB");
    if (!dev) dev = "/dev/fb0";
    fb_fd = open(dev, O_RDWR);
    if (fb_fd < 0) { perror("open /dev/fb0"); return falseblnr; }

    struct fb_var_screeninfo vs;
    struct fb_fix_screeninfo fs;
    ioctl(fb_fd, FBIOGET_VSCREENINFO, &vs);
    ioctl(fb_fd, FBIOGET_FSCREENINFO, &fs);
    fprintf(stderr, "[kindle] fb %ux%u @%ubpp stride=%u\n",
            vs.xres, vs.yres, vs.bits_per_pixel, fs.line_length);
    if (vs.bits_per_pixel != 8)
        fprintf(stderr, "[kindle] WARNING: expected 8bpp, got %u\n",
                vs.bits_per_pixel);

    fb_stride = fs.line_length;
    fb_size   = (size_t)fs.line_length * vs.yres;
    fb_mem    = mmap(NULL, fb_size, PROT_READ|PROT_WRITE, MAP_SHARED, fb_fd, 0);
    if (fb_mem == MAP_FAILED) { perror("mmap fb"); return falseblnr; }
    memset(fb_mem, 0xFF, fb_size);
    return trueblnr;
}
LOCALPROC fb_close(void) {
    if (fb_mem && fb_mem != MAP_FAILED) munmap(fb_mem, fb_size);
    if (fb_fd >= 0) close(fb_fd);
    fb_mem = NULL; fb_fd = -1;
}

LOCALFUNC blnr touch_open(void) {
    const char *dev = getenv("MINIVMAC_TOUCH");
    if (!dev) dev = "/dev/input/event1";
    touch_fd = open(dev, O_RDONLY | O_NONBLOCK);
    if (touch_fd < 0) { perror("open touch"); return falseblnr; }

    struct input_absinfo ai;
    if (ioctl(touch_fd, EVIOCGABS(ABS_MT_POSITION_X), &ai) == 0)
        { tx_min = ai.minimum; tx_max = ai.maximum; }
    if (ioctl(touch_fd, EVIOCGABS(ABS_MT_POSITION_Y), &ai) == 0)
        { ty_min = ai.minimum; ty_max = ai.maximum; }
    fprintf(stderr, "[kindle] touch X[%d-%d] Y[%d-%d]\n",
            tx_min, tx_max, ty_min, ty_max);
    memset(slot_id, -1, sizeof(slot_id));
    return trueblnr;
}
LOCALPROC touch_close(void) {
    if (touch_fd >= 0) close(touch_fd);
    touch_fd = -1;
}

/* ── Stubs for Mini vMac platform callbacks ──────────────────────────── *
 * The core calls these; provide minimal no-op implementations.          */
GLOBALPROC WarnMsgCStr(const char *s) { fprintf(stderr, "[vmac] %s\n", s); }
GLOBALPROC MySound_SecondNotify(void) {}
GLOBALPROC MySound_BeginBlock(void)   {}
GLOBALPROC MySound_EndBlock(void)     {}

/* ── main ────────────────────────────────────────────────────────────── */
int main(int argc, char *argv[]) {
    (void)argc; (void)argv;

    signal(SIGINT,  on_signal);
    signal(SIGTERM, on_signal);

    if (!fb_open())    return 1;
    if (!touch_open()) return 1;

    /* Zero Mini vMac's OS-glue variables */
    ZapOSGLUVars();

    /* Allocate emulator RAM, load ROM, verify checksum */
    if (!ReserveAllocAll()) {
        fprintf(stderr, "[kindle] ReserveAllocAll failed.\n"
                        "         Ensure vMac.ROM is in the working directory.\n");
        return 1;
    }

    /* Draw initial state */
    draw_kbd_indicator();
    eink_full_gc16();

    const int64_t TICK_US = 1000000LL / 60;
    int64_t next_tick = time_us();
    int gc16_ctr = 0;

    while (!g_quit) {
        int64_t now = time_us();
        if (now < next_tick) { sleep_us(next_tick - now); continue; }
        next_tick += TICK_US;

        poll_touch();

        /* Run one emulated frame — calls HaveChangedScreenBuff if dirty */
        DoEmulateOneTick();

        /* Periodic GC16 to clear A2 ghosting (~5 s @ 60 Hz) */
        if (++gc16_ctr >= 300) {
            gc16_ctr = 0;
            if (kbd_visible) render_keyboard();
            draw_kbd_indicator();
            eink_full_gc16();
        }
    }

    UnReserveAlloc();
    touch_close();
    fb_close();
    return 0;
}
